"use strict";

const state = { messages: [], moments: [], platform: "twitch", videoId: "untitled" };
const $ = (selector, scope = document) => scope.querySelector(selector);

function parseTime(value) {
  if (typeof value === "number") return value;
  const text = String(value ?? "").trim();
  if (/^PT/.test(text)) { const h = Number((text.match(/(\d+)H/) || [0, 0])[1]); const m = Number((text.match(/(\d+)M/) || [0, 0])[1]); const s = Number((text.match(/([\d.]+)S/) || [0, 0])[1]); return h * 3600 + m * 60 + s; }
  const pieces = text.split(":").map(Number); if (pieces.length === 3) return pieces[0] * 3600 + pieces[1] * 60 + pieces[2]; if (pieces.length === 2) return pieces[0] * 60 + pieces[1]; return Number(text);
}
function normalizeRow(row) {
  if ("content_offset_seconds" in row) return { timestamp: Number(row.content_offset_seconds), text: row.message?.body || "", author: row.commenter?.display_name || "" };
  return { timestamp: parseTime(row.timestamp ?? row.time ?? row.offset), text: String(row.message ?? row.text ?? row.content ?? ""), author: String(row.author ?? row.user ?? row.username ?? "") };
}
function parseCsv(text) {
  const lines = text.replace(/^\uFEFF/, "").trim().split(/\r?\n/); const headers = lines.shift().split(",").map((v) => v.trim());
  return lines.filter(Boolean).map((line) => { const values = line.match(/(?:^|,)("(?:[^"]|"")*"|[^,]*)/g).map((v) => v.replace(/^,/, "").replace(/^"|"$/g, "").replace(/""/g, '"')); return Object.fromEntries(headers.map((header, i) => [header, values[i] ?? ""])); });
}
function loadFile(file) {
  const reader = new FileReader();
  reader.onload = () => { try { const raw = String(reader.result); const payload = file.name.toLowerCase().endsWith(".csv") ? parseCsv(raw) : JSON.parse(raw); const rows = Array.isArray(payload) ? payload : payload.comments || []; state.messages = rows.map(normalizeRow).filter((m) => Number.isFinite(m.timestamp) && m.text.trim()).sort((a,b) => a.timestamp-b.timestamp); if (!state.messages.length) throw new Error("No valid timestamp/message pairs were found."); $("#file-status").textContent = `${file.name} · ${state.messages.length.toLocaleString()} messages ready`; } catch (error) { state.messages = []; $("#file-status").textContent = `Could not read file: ${error.message}`; } };
  reader.readAsText(file);
}
function keywords(messages) { const ignored = new Set(["the","and","that","this","with","what","for","you","are","was","but","have","just","lol","lmao"]); const counts = new Map(); messages.forEach((message) => (message.text.toLowerCase().match(/[a-z][a-z0-9_']{2,}/g) || []).forEach((word) => { if (!ignored.has(word)) counts.set(word, (counts.get(word) || 0) + 1); })); return [...counts].sort((a,b) => b[1]-a[1]).slice(0,5).map(([word]) => word); }
function findMoments() {
  const windowSeconds = Number($("#window-seconds").value), minMessages = Number($("#min-messages").value), threshold = Number($("#z-threshold").value); if (!(windowSeconds > 0 && minMessages > 0 && threshold >= 0)) throw new Error("Check the detection settings.");
  const buckets = new Map(); state.messages.forEach((message) => { const index = Math.floor(message.timestamp / windowSeconds); buckets.set(index, [...(buckets.get(index) || []), message]); }); const last = Math.max(...buckets.keys()); const counts = Array.from({length:last+1}, (_, i) => (buckets.get(i) || []).length); const mean = counts.reduce((a,b) => a+b, 0) / counts.length; const deviation = Math.sqrt(counts.reduce((sum,count) => sum + (count-mean) ** 2, 0) / counts.length);
  return counts.map((count, index) => { const zScore = deviation ? (count-mean)/deviation : 0; const messages = buckets.get(index) || []; return { timestamp:index*windowSeconds+windowSeconds/2, windowStart:index*windowSeconds, windowEnd:(index+1)*windowSeconds, messageCount:count, baselineCount:Number(mean.toFixed(2)), zScore:Number(zScore.toFixed(2)), sampleMessages:messages.slice(0,5).map((m) => m.text), keywords:keywords(messages) }; }).filter((moment) => moment.messageCount >= minMessages && moment.zScore >= threshold).sort((a,b) => b.zScore-a.zScore || b.messageCount-a.messageCount).slice(0,25);
}
function clock(seconds) { const s = Math.floor(seconds), h = Math.floor(s/3600), m = Math.floor(s%3600/60); return [h,m,s%60].map((v,i) => i === 0 && h === 0 ? null : String(v).padStart(2,"0")).filter((v) => v !== null).join(":"); }
function render() { const list = $("#moment-list"); list.replaceChildren(); $("#results").hidden=false; $("#result-title").textContent = `${state.moments.length} candidate moment${state.moments.length === 1 ? "" : "s"}`; $("#message-count").textContent=state.messages.length.toLocaleString(); $("#moment-count").textContent=state.moments.length; $("#peak-rate").textContent=Math.max(0,...state.moments.map((m) => m.messageCount)); $("#empty-state").hidden=state.moments.length !== 0; state.moments.forEach((moment, index) => { const card = $("#moment-template").content.cloneNode(true); $(".moment-time",card).textContent=clock(moment.timestamp); $("h3",card).textContent=`Moment ${String(index+1).padStart(2,"0")} · ${moment.messageCount} messages`; $(".score",card).textContent=`z-score ${moment.zScore}`; $(".keywords",card).textContent=moment.keywords.length ? `CHAT SIGNAL: ${moment.keywords.join(" · ")}` : "CHAT SIGNAL: —"; $("blockquote",card).textContent=moment.sampleMessages.map((m) => `“${m}”`).join("  "); list.append(card); }); $("#results").scrollIntoView({behavior:"smooth",block:"start"}); }
function download(kind) { const payload = kind === "json" ? JSON.stringify({platform:state.platform,videoId:state.videoId,moments:state.moments},null,2) : ["timestamp,message_count,z_score,keywords",...state.moments.map((m) => `${clock(m.timestamp)},${m.messageCount},${m.zScore},"${m.keywords.join(" | ")}"`)].join("\n"); const blob = new Blob([payload],{type:kind === "json" ? "application/json" : "text/csv"}); const link = Object.assign(document.createElement("a"),{href:URL.createObjectURL(blob),download:`${state.platform}-${state.videoId}-moments.${kind}`}); link.click(); URL.revokeObjectURL(link.href); }
$("#chat-file").addEventListener("change",(event)=>event.target.files[0] && loadFile(event.target.files[0])); $("#upload-zone").addEventListener("dragover",(event)=>{event.preventDefault(); $("#upload-zone").classList.add("dragging")}); $("#upload-zone").addEventListener("dragleave",()=>$("#upload-zone").classList.remove("dragging")); $("#upload-zone").addEventListener("drop",(event)=>{event.preventDefault(); $("#upload-zone").classList.remove("dragging"); const file=event.dataTransfer.files[0]; if(file) loadFile(file)});
$("#analysis-form").addEventListener("submit",(event)=>{event.preventDefault(); if(!state.messages.length){$("#file-status").textContent="Choose a chat JSON or CSV file before analyzing.";return;} try {state.platform=$("#platform").value;state.videoId=$("#video-id").value.trim() || "untitled";state.moments=findMoments();render();}catch(error){$("#file-status").textContent=error.message;}}); $("#download-json").addEventListener("click",()=>download("json")); $("#download-csv").addEventListener("click",()=>download("csv"));
